---

embeddeddisco-discovery:
  path: /disco
  defaults: {
    _controller: 'SimpleSAML\Module\embeddeddisco\Controller\Discovery::main'
  }
  methods: [GET]

embeddeddisco-login:
  path: /login
  defaults: {
    _controller: 'SimpleSAML\Module\embeddeddisco\Controller\Login::main'
  }
  methods: [GET]

embeddeddisco-session:
  path: /session
  defaults: {
    _controller: 'SimpleSAML\Module\embeddeddisco\Controller\Login::session'
  }
  methods: [GET]

embeddeddisco-entities:
  path: /entities
  defaults: {
    _controller: 'SimpleSAML\Module\embeddeddisco\Controller\Discovery::entities'
  }
  methods: [GET]

embeddeddisco-select:
  path: /select
  defaults: {
    _controller: 'SimpleSAML\Module\embeddeddisco\Controller\Discovery::select'
  }
  methods: [GET]

embeddeddisco-callback:
  path: /callback
  defaults: {
    _controller: 'SimpleSAML\Module\embeddeddisco\Controller\Discovery::callback'
  }
  methods: [GET]

embeddeddisco-status:
  path: /status
  defaults: {
    _controller: 'SimpleSAML\Module\embeddeddisco\Controller\Status::status'
  }
  methods: [GET]

embeddeddisco-federation-configuration:
  path: /federation/.well-known/openid-federation
  defaults: {
    _controller: 'SimpleSAML\Module\embeddeddisco\Controller\FederationEntity::configuration'
  }
  methods: [GET]

embeddeddisco-federation-list:
  path: /federation/list
  defaults: {
    _controller: 'SimpleSAML\Module\embeddeddisco\Controller\FederationEntity::list'
  }
  methods: [GET]

embeddeddisco-federation-fetch:
  path: /federation/fetch
  defaults: {
    _controller: 'SimpleSAML\Module\embeddeddisco\Controller\FederationEntity::fetch'
  }
  methods: [GET]
